### PR TITLE
[ADDED]: Email verification

### LINKED ISSUE #12: email verification

### PR DESCRIPTION
**Pull request by MCoder86A**
#### Resolves #12
- [x] Generate auth token and sent to email
- [x] Verification of token and mark the user as email verified
- [x] API to check if user is verified or not
- [x] Front end
- [x] Tested 👍 

Before deploying please set environment variable as shown [here](https://github.com/shelcia/mocker/pull/44/commits/6d71494b1f1c7aeb65e9915290c3399ca6e82ab7#diff-0e320819a20d54d985ec682f82c0e0be462b12a8a26e57a339cb68947fcfeeb6R5-R6)
```
EMAIL_ID = "email_id"
EMAIL_PWD = "password"
```
I have used gmail as a smtp server.. Password can be generated from security section and it requires 2 step verification

### CODE REVIEW

**Comment by MCoder86A** [comment]
This PR will resolve #12

**Comment by MCoder86A** [comment]
EMAIL-VERIFICATION-rdev43269-gmail-com-Gmail

#### Clicking the link shows:
`{"status":"200","message":"Verified"}`
and also update the database

#### Putting or changing the token in the link shows:
`{"status":"400","message":"Something wrong"}`

**Comment by MCoder86A** [comment]
Resolves #12 

> #### Resolves #12
> * [x]  Generate auth token and sent to email
> * [x]  Verification of token and mark the user as email verified
> * [x]  API to check if user is verified or not
> * [x]  Front end not done yet
> * [x]  Tested 👍
> 
> Before deploying please set environment variable as shown [here](https://github.com/shelcia/mocker/pull/44/commits/6d71494b1f1c7aeb65e9915290c3399ca6e82ab7#diff-0e320819a20d54d985ec682f82c0e0be462b12a8a26e57a339cb68947fcfeeb6R5-R6)
> 
> ```
> EMAIL_ID = "email_id"
> EMAIL_PWD = "password"
> ```
> 
> I have used gmail as a smtp server.. Password can be generated from security section and it requires 2 step verification

**Comment by MCoder86A** [comment]
https://user-images.githubusercontent.com/56883128/207578919-d3f09fdb-48e8-4d6c-8c62-a3327c85d68f.mov

**Review by shelcia — APPROVED** [review]

**Comment by MCoder86A** [comment]
> Env Variables are added. Please Verify now

@shelcia  Yes its working now. I got the verification link and got verified.
But "Verify button" needs a page refresh after login to show up. I should fix that as well

**Pull request merged**
