### PR TITLE
Grouped the various fields based on the category in add resource dropdown

### PR DESCRIPTION
**Pull request by abdullahranginwala**
This PR is with regards to issue #23. I've grouped the various choices, and added the appropriate MUI subhead for each of the category.

### CODE REVIEW

**Comment by shelcia** [comment]
@abdullahranginwala  Not working  check your code https://deploy-preview-36--mocker-gen.netlify.app/

**Comment by MCoder86A** [comment]
@abdullahranginwala May I know if you are working on it ? I have almost fix the issue. If you are not working on it please let me know. 

Thanks.

**Comment by abdullahranginwala** [comment]
@shelcia Is this the expected output?
Screenshot 2022-12-09 at 4 47 04 PM

**Comment by abdullahranginwala** [comment]
@MCoder86A Sure! If you have a solution ready I wouldn't mind if you make a PR.

**Comment by MCoder86A** [comment]
> @shelcia Is this the expected output? Screenshot 2022-12-09 at 4 47 04 PM

There are some issue which I found was:
* Items are not clickable
* Category name is not visible in day mode
* App breaks as soon as clicked on the drop down as shown in the video

https://user-images.githubusercontent.com/56883128/206698059-b9885af3-2d1b-4c9b-b93b-bd52cdf6e5d8.mp4

**Pull request closed without merging**
